from collections import defaultdict
from dataclasses import dataclass
from datetime import date, timedelta
from typing import Optional


@dataclass
class GoalInput:
    id: int
    title: str
    priority: int
    weekly_hours_target: float


@dataclass
class SessionOutput:
    goal_id: int
    day_of_week: int
    title: str
    duration_minutes: int
    notes: str


def normalize_week_start(input_date: Optional[date]) -> date:
    base = input_date or date.today()
    return base - timedelta(days=base.weekday())


def generate_sessions(goals: list[GoalInput], available_hours: float) -> list[SessionOutput]:
    total_minutes = int(available_hours * 60)
    if not goals or total_minutes < 30:
        return []

    block = 30
    usable_minutes = total_minutes - (total_minutes % block)
    if usable_minutes == 0:
        return []

    weighted_scores = [max(1, g.priority) * max(0.5, g.weekly_hours_target) for g in goals]
    score_sum = sum(weighted_scores)
    per_goal_minutes: dict[int, int] = {}

    for goal, score in zip(goals, weighted_scores):
        raw = usable_minutes * (score / score_sum)
        rounded = int(raw // block) * block
        per_goal_minutes[goal.id] = max(block, rounded)

    allocated = sum(per_goal_minutes.values())
    while allocated > usable_minutes:
        reducible = [g.id for g in goals if per_goal_minutes[g.id] > block]
        if not reducible:
            break
        for goal_id in reducible:
            if allocated <= usable_minutes:
                break
            per_goal_minutes[goal_id] -= block
            allocated -= block

    while allocated < usable_minutes:
        for g in goals:
            if allocated >= usable_minutes:
                break
            per_goal_minutes[g.id] += block
            allocated += block

    day_loads = defaultdict(int)
    sessions: list[SessionOutput] = []
    ordered_goals = sorted(goals, key=lambda g: (-g.priority, g.title.lower()))

    for goal in ordered_goals:
        minutes_left = per_goal_minutes[goal.id]
        while minutes_left > 0:
            best_day = min(range(7), key=lambda d: day_loads[d])
            duration = min(90, minutes_left)
            if duration % block != 0:
                duration -= duration % block
            if duration == 0:
                duration = block
            sessions.append(
                SessionOutput(
                    goal_id=goal.id,
                    day_of_week=best_day,
                    title=f"{goal.title} focus session",
                    duration_minutes=duration,
                    notes="Generated by planner based on priority and weekly target.",
                )
            )
            day_loads[best_day] += duration
            minutes_left -= duration

    return sorted(sessions, key=lambda s: (s.day_of_week, s.goal_id))
